spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://dpg-cslmhh3v2p9s7388hh0g-a.ohio-postgres.render.com:${RDS_PORT:5432}/tarefas_8fq7
    username: admin
    password: ANLXFmc8EB21hkfT8TrJZK55hlbLppFU
  web:
    resources:
      static-locations: classpath:/static/



