spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:tarefas}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:1234}
  web:
    resources:
      static-locations: classpath:/static/



